
backend:
  name: git-gateway
  branch: main # or master, depending on your default branch

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "announcements"
    label: "Announcements"
    folder: "src/data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["General", "Academic", "Sports", "Holiday", "Admissions", "Event"]
        }
      - { label: "Created At", name: "created_at", widget: "datetime" }

